export default {
	APP_NAME: `Jira Issues Report`,
	APP_VERSION: `4.5`,
	ESTIMATION_READY: `estimation-ready`,
	AC_WRITTEN: `ac-written`,
	AC_REVIEW_READY: `ac-review-ready`,
	AC_REVIEW_COMPLETE: `ac-review-complete`,
	ITD_CLARFICIATION: `itd-clarification`,
	ETD_CLARFICIATION: `etd-clarification`,
	PENDING_FIGMA: `pending-figma`,
	PENDING_DISCUSSION: `pending-discussion`,
	PEER_REVIEW_1: `peer-review-1`,
	ESTIMATE_DETAIL_LEVEL: "estimate-detail-level",
	ESTIMATE_EXIT_DETAIL_LEVEL: "estimate-exit-detail-level",
	ESTIMATE_HIGH_LEVEL_SUFFIX: "99",
	ESTIMATE_DETAIL_LEVEL_SUFFIX: "39",
	EMPTY_REPORT_TEMPLATE: {
		status: "OK",
		data: [],
		generatedDateTime: new Date().toISOString(),
	},
};
